source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExpSwift_Example' do
  pod "ExpSwift", :path => "../"
end

target 'ExpSwift_Tests' do
  pod "ExpSwift", :path => "../"

  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
