source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExpSwift_Example', :exclusive => true do
  pod "ExpSwift", :path => "../"
end

target 'ExpSwift_Tests', :exclusive => true do
  pod "ExpSwift", :path => "../"

  
end
