source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExpSwift_Example' do
  pod "ExpSwift", :path => "../"
end

target 'ExpSwift_Tests' do
  pod "ExpSwift", :path => "../"

  
end
